name: Merge essays into main

on:
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'     
        required: true
  #push:
    #branches:
      #- essays

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout essays branch
        uses: actions/checkout@v2
        with:
          ref: essays

      - name: Move files to specific folder
        run: |
          rm -rf src/routes/texts/*
          mkdir -p src/routes/texts
          rsync -u ./*.md src/routes/texts
          git add .
          git stash
          
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Merge essays branch
        run: git merge --no-commit --no-ff ${{ github.sha }}

      - name: Commit changes
        run: |
          git stash apply
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Merge essays branch into main" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
